name: FarmingChest
version: "1.3"
main: com.codegen.FarmingChest.FarmingChest
api-version: '1.20'
depend: [Vault, DecentHolograms]
commands:
  farmingchest:
    description: Main command for FarmingChest.
    aliases: [fc, fchest]
permissions:
  farmingchest.give:
    description: Allows the user to give farming chests.
    default: op
  farmingchest.reload:
    description: Allows the user to reload the plugin configuration.
    default: op
